### ISSUE TITLE
Adding Dark Theme.

### ISSUE THREAD

**Issue by akarshansonkar** [akarshansonkar/Weather-project#1]
Add Theme changing feature

**Comment by utkarsh4321** [comment]
can you give more description about it?

**Comment by akarshansonkar** [comment]
> can you give more description about it?

Its like you need to add dark theme, light theme functionality to every page in this project.
It should operate using a button which must be on the top right corner.
Such that user can switch between the dark and light theme just by clicking that button.

**Comment by utkarsh4321** [comment]
ok can you assign this to me

**Comment by adsingh14** [comment]
Let me add dark theme mode. I need to get assigned from your side.

**Comment by akarshansonkar** [comment]
Assigned to @utkarsh4321 for adding Dark Theme in every page.

**Comment by utkarsh4321** [comment]
@akarshansonkar  where i will write js for dark theme.

**Comment by akarshansonkar** [comment]
Make sure you need to write the code for dark theme inside partial folder with the file extension " .hbs".
write the js with the html code inside that file and simply import that file in every pages where ever you need to add dark theme.
